// SPDX-License-Identifier: AGPL-3.0-only
#include "UI/Localization.hpp"

namespace zyron::ui::i18n {

// {English text exactly as written in TRANS("..."), Russian text}. UTF-8 (the build uses /utf-8).
// A key with "%s" also matches outside messages that vary in that part (see translateMessage()).
// DJ conventions stay English on purpose: PLAY, PAUSE, CUE, SYNC, LOOP, IN, OUT, MASTER, X-F L, X-F R, THRU, VOC, DRUM,
// BASS, OTHER, BPM, Key, REC, SPLIT, STEMS, dB.
const std::vector<std::pair<const char*, const char*>>& russianStrings() {
  static const std::vector<std::pair<const char*, const char*>> table = {
      // Top bar, tabs and status line (MainComponent)
      {"2 DECKS", "2 ДЕКИ"},
      {"4 DECKS", "4 ДЕКИ"},
      {"AUTOMIX", "АВТОМИКС"},
      {"SETTINGS", "ОПЦИИ"},
      {"LIBRARY", "БИБЛИОТЕКА"},
      {"AUTOMIX QUEUE", "ОЧЕРЕДЬ МИКСА"},
      {"Mixes the analysed tracks of the library automatically", "Автоматически микширует проанализированные треки библиотеки"},
      {"DSP: %cpu% | SR: %sr% Hz | xruns: %xr% | dropped: %dr%", "ЦП: %cpu% | SR: %sr% Гц | сбоев: %xr% | потеряно: %dr%"},
      {"That track cannot be moved: it has started or is being prepared", "Этот трек нельзя переместить: он уже начат или готовится"},
      {"That track cannot be removed: it has started or is being prepared", "Этот трек нельзя убрать: он уже начат или готовится"},
      {"Nothing to jump to: start Automix first", "Некуда переходить: сначала запустите автомикс"},
      {"Beat loops need a BPM: this track has not been analysed yet", "Для лупа по долям нужен BPM: трек ещё не проанализирован"},
      {"Could not save the marker", "Не удалось сохранить метку"},
      {"Load failed", "Ошибка загрузки"},
      // Settings tabs and General
      {"Drag to resize | Right-click: default size", "Тяните, чтобы изменить размер | Правый клик: размер по умолчанию"},
      {"Prepare stems on load", "Готовить стемы при загрузке"},
      {"Separates every track you load into vocals, drums, bass and other in the background, so the stem controls work right away (uses the CPU for about a minute per track)", "Разделяет каждый загруженный трек на вокал, барабаны, бас и остальное в фоне, чтобы регуляторы стемов работали сразу (около минуты работы процессора на трек)"},
      {"Stems: preparing %n%", "Стемы готовятся: %n%"},
      {"Stems: waiting to start", "Стемы: в очереди"},
      {"Click a stem button to separate the track", "Нажмите кнопку стема, чтобы разделить трек"},
      {"Stems failed: click SPLIT to retry", "Стемы не получились: нажмите SPLIT ещё раз"},
      {"General", "Общие"},
      {"Language", "Язык"},
      {"Audio Device", "Аудиоустройство"},
      {"Hardware Diagnostics", "Диагностика оборудования"},
      // Markers (waveform labels and the deck mark menu)
      {"MIX IN", "МИКС ВХ"},
      {"MIX OUT", "МИКС ВЫХ"},
      {"DROP", "ДРОП"},
      {"BREAK", "БРЕЙК"},
      {"INTRO", "ИНТРО"},
      {"OUTRO", "АУТРО"},
      {"MARK", "МЕТКА"},
      // Deck
      {"DECK", "ДЕК"},
      {"No Track Loaded", "Трек не загружен"},
      {"Untitled Track", "Трек без названия"},
      {"Separate the track into vocals, drums, bass and other (neural network, runs in the background)", "Разделить трек на вокал, барабаны, бас и остальное (нейросеть, работает в фоне)"},
      {"Separate the track into vocals, drums, bass and other (runs in the background)", "Разделить трек на вокал, барабаны, бас и остальное (работает в фоне)"},
      {"Waiting for the stem separation to start", "Ожидание начала разделения на стемы"},
      {"Separating the track with the neural network", "Нейросеть разделяет трек"},
      {"The deck plays from its stems: use the VOC / DRUM / BASS / OTHER controls", "Дека играет из стемов: используйте регуляторы VOC / DRUM / BASS / OTHER"},
      {"Stem separation failed:", "Не удалось разделить на стемы:"},
      {"Mark the playhead as a mix point, drop or breakdown (the AI proposes them automatically)", "Отметить позицию воспроизведения как точку микса, дроп или брейк (ИИ предлагает их автоматически)"},
      {"Mark the playhead as", "Отметить позицию как"},
      {"Mix in (where this track may come in)", "Вход в микс (где этот трек может вступить)"},
      {"Mix out (where the mix out should begin)", "Выход из микса (где должен начаться выход)"},
      {"Drop", "Дроп"},
      {"Breakdown", "Брейк"},
      {"Intro", "Интро"},
      {"Outro", "Аутро"},
      {"Remove the marker nearest to the playhead", "Удалить ближайшую к позиции метку"},
      {"Jump to", "Перейти к"},
      {"Stem volume (0 to 1)", "Громкость стема (0–1)"},
      {"Pitch (%)", "Питч (%)"},
      // Mixer
      {"CH", "КАН"},
      {"Channel gain (dB)", "Усиление канала (дБ)"},
      {"EQ high (dB)", "Эквалайзер, верха (дБ)"},
      {"EQ mid (dB)", "Эквалайзер, середина (дБ)"},
      {"EQ low (dB)", "Эквалайзер, низы (дБ)"},
      {"DJ filter (-1 low-pass, +1 high-pass)", "DJ-фильтр (-1 НЧ, +1 ВЧ)"},
      {"Channel volume (0 to 1)", "Громкость канала (0–1)"},
      {"Master gain (dB)", "Общий уровень (дБ)"},
      {"Crossfader (-1 left, +1 right)", "Кроссфейдер (-1 влево, +1 вправо)"},
      {"Constant Power", "Равная мощность"},
      {"Linear", "Линейная"},
      {"Cut", "Резкая"},
      // Parameter slider
      {"Right-click: reset to default | Double-click: type a value", "Правый клик: сброс | Двойной клик: ввести значение"},
      {"Set value", "Задать значение"},
      {"Range %min% to %max%, default %def%", "Диапазон от %min% до %max%, по умолчанию %def%"},
      {"Value", "Значение"},
      {"Cancel", "Отмена"},
      // Library
      {"Scan Folder...", "Сканировать папку..."},
      {"Load A", "В деку A"},
      {"Load B", "В деку B"},
      {"Load C", "В деку C"},
      {"Load D", "В деку D"},
      {"Mix next", "Микс далее"},
      {"Search tracks by artist, title, genre, BPM, key, path...", "Поиск по исполнителю, названию, жанру, BPM, тональности, пути..."},
      {"Select Music Folder to Scan", "Выберите папку с музыкой для сканирования"},
      {"Mix the selected track in live: the playing deck is mixed into it", "Вмикшировать выбранный трек вживую: играющая дека перейдёт в него"},
      {"Title", "Название"},
      {"Artist", "Исполнитель"},
      {"Energy", "Энергия"},
      {"Time", "Время"},
      {"Status", "Статус"},
      {"Genre", "Жанр"},
      {"File Path", "Путь к файлу"},
      {"%n tracks", "треков: %n"},
      {"(filtered from %n)", "(отфильтровано из %n)"},
      {"scanning", "сканирование"},
      {"preparing: %n tasks left", "подготовка: осталось задач: %n"},
      {"min", "мин"},
      {"s", "с"},
      {"scan failed", "сбой сканирования"},
      {"(Untitled)", "(Без названия)"},
      {"Ready (%n failed)", "Готово (ошибок: %n)"},
      {"Ready", "Готово"},
      {"Preparing", "Подготовка"},
      {"Load to deck A", "Загрузить в деку A"},
      {"Load to deck B", "Загрузить в деку B"},
      {"Load to deck C", "Загрузить в деку C"},
      {"Load to deck D", "Загрузить в деку D"},
      {"Mix next (live)", "Микс далее (вживую)"},
      {"Analyse now (already prepared)", "Анализировать сейчас (уже подготовлен)"},
      {"Analyse now (prepare this track first)", "Анализировать сейчас (сначала подготовить трек)"},
      {"Re-analyse with the AI (tempo, key, markers)", "Переанализировать с ИИ (темп, тональность, метки)"},
      {"Show in file manager", "Показать в проводнике"},
      {"Copy file path", "Копировать путь к файлу"},
      {"Remove from library...", "Удалить из библиотеки..."},
      {"Remove from library", "Удаление из библиотеки"},
      {"Remove \"%t\" from the library?\nThe file on disk is not touched.", "Удалить «%t» из библиотеки?\nФайл на диске не затрагивается."},
      {"Remove", "Удалить"},
      // Automix workspace (transitions, mix style)
      {"Transition", "Переход"},
      {"Blend", "Микс"},
      {"Stem blend", "Микс стемов"},
      {"Cut on the drop", "Обрез на дропе"},
      {"Filter sweep", "Фильтр-свип"},
      {"Crossfade", "Кроссфейд"},
      {"Loop roll", "Луп-ролл"},
      {"Brake", "Тормоз"},
      {"Beat loop", "Луп бита"},
      {"BEAT LOOP", "ЛУП БИТА"},
      {"Double drop", "Двойной дроп"},
      {"Echo out", "Уход в эхо"},
      {"Reverb out", "Уход в реверб"},
      {"DOUBLE DROP", "ДВОЙНОЙ ДРОП"},
      {"ECHO OUT", "УХОД В ЭХО"},
      {"REVERB OUT", "УХОД В РЕВЕРБ"},
      {"Scratch", "Скретч"},
      // Transition regions drawn on the waveforms (labels come from the engine in English, upper case)
      {"BASS SWAP", "СВАП БАСА"},
      {"FILTER FADE", "ФИЛЬТР"},
      {"LOOP ROLL", "ЛУПРОЛЛ"},
      {"SCRATCH", "СКРЕТЧ"},
      {"BRAKE", "ТОРМОЗ"},
      {"CUT", "ОБРЫВ"},
      {"LOOP", "ЛУП"},
      {"QUICK CUT", "БЫСТРЫЙ ОБРЫВ"},
      {"VOLUME CROSSFADE", "КРОССФЕЙД"},
      {"STEM BLEND", "МИКС СТЕМОВ"},
      // Manual scratch menu (deck SCR button)
      {"SCR", "СКР"},
      {"Scratch (the deck performs it in time with the track)", "Скретч (дека выполняет его в такт треку)"},
      {"Baby scratch", "Бэйби-скретч"},
      {"Transformer", "Трансформер"},
      {"Chirp", "Чирп"},
      {"Flare", "Флэйр"},
      {"Crab", "Краб"},
      {"Scribble", "Скриббл"},
      {"Tear", "Тир"},
      {"Stab", "Стэб"},
      {"Drag", "Драг"},
      {"Backspin (stops the deck)", "Бэкспин (дека остановится)"},
      {"1 beat", "1 доля"},
      {"2 beats", "2 доли"},
      {"Scratches need a BPM: this track has not been analysed yet", "Для скретча нужен BPM: трек ещё не проанализирован"},
      {"Scratches need a playing deck", "Скретч возможен только на играющей деке"},
      {"Auto (profile)", "Авто (по профилю)"},
      {"That transition has already started and cannot be changed", "Этот переход уже начался, его нельзя изменить"},
      {"MIX STYLE", "СТИЛЬ МИКСА"},
      {"Mode", "Режим"},
      {"Smooth", "Плавно"},
      {"Club", "Клуб"},
      {"Battle", "Баттл"},
      {"Custom", "Свой"},
      {"Transition length", "Длина перехода"},
      {"%s beats", "%s долей"},
      {"Order", "Порядок"},
      {"Smooth, like a streaming crossfade but on the beat", "Плавно, как в стриминге, но в такт"},
      {"Club: blends, filter sweeps, loop rolls and brakes", "Клуб: миксы, фильтры, луп-роллы и тормоза"},
      {"Hard: DJ battle, scratches and cuts on the drop", "Жёстко: DJ-баттл, скретчи и обрезы на дропе"},
      {"Your own choice of techniques", "Ваш собственный набор приёмов"},
      {"Picks a ready-made mixing style; the techniques below follow it", "Готовый стиль микса; приёмы ниже подстраиваются под него"},
      {"How long a mix between two tracks lasts", "Сколько длится микс между двумя треками"},
      // Automix queue
      {"Up", "Вверх"},
      {"Down", "Вниз"},
      {"Jump to transition", "К переходу"},
      {"Automix is off: press AUTOMIX and the AI plans a set from the analysed tracks.", "Автомикс выключен: нажмите АВТОМИКС, и ИИ составит сет из проанализированных треков."},
      {"Move the playing track to a little before the transition the AI planned, to hear the mix", "Перемотать играющий трек чуть раньше запланированного ИИ перехода, чтобы услышать микс"},
      {"Play the selected track earlier (only tracks that have not started)", "Играть выбранный трек раньше (только треки, которые ещё не начались)"},
      {"Play the selected track later", "Играть выбранный трек позже"},
      {"Take the selected track out of the set", "Убрать выбранный трек из сета"},
      {"Fit", "Подх."},
      {"Mix in", "Вход"},
      {"Mix out", "Выход"},
      {"Why the AI chose it", "Почему ИИ выбрал его"},
      {"Planned set", "Запланированный сет"},
      {"playing %a of %b", "играет %a из %b"},
      {"stopped at %a of %b", "остановлен на %a из %b"},
      {"next", "далее"},
      {"Opening track chosen for the start of the energy curve", "Открывающий трек выбран для начала кривой энергии"},
      // Audio settings and diagnostics
      {"Audio API", "Аудио API"},
      {"Output device", "Устройство вывода"},
      {"Sample rate", "Частота дискретизации"},
      {"Buffer size", "Размер буфера"},
      {"frames", "сэмплов"},
      {"Test tone (440 Hz)", "Тестовый тон (440 Гц)"},
      {"Turn your speakers down first: the tone is a plain sine and is louder than it looks.", "Сначала убавьте громкость колонок: тон — чистая синусоида и звучит громче, чем кажется."},
      {"System default", "Системное по умолчанию"},
      {"Detecting hardware...", "Определение оборудования..."},
      // Background queue
      {"AI Background Task Queue", "Фоновая очередь задач ИИ"},
      {"Active: 0", "Активно: 0"},
      {"Active tasks:", "Активных задач:"},
      {"Task Name", "Задача"},
      {"Priority", "Приоритет"},
      {"Device", "Устройство"},
      {"Progress", "Прогресс"},
      {"Clear Finished", "Очистить завершённые"},
      {"Cancel Task", "Отменить задачу"},
      {"Queued", "В очереди"},
      {"Running", "Выполняется"},
      {"Completed", "Завершено"},
      {"Cancelled", "Отменено"},
      {"Failed", "Ошибка"},
      {"Interactive", "Интерактивный"},
      {"Background", "Фоновый"},
      // Model manager
      {"AI Model Manager", "Менеджер моделей ИИ"},
      {"Manage models for Stems, BPM, Key and Analysis. Permissive weights verified.", "Управление моделями для стемов, BPM, тональности и анализа. Лицензии весов проверены."},
      {"Model", "Модель"},
      {"Task", "Задача"},
      {"Ver", "Верс."},
      {"License", "Лицензия"},
      {"Size", "Размер"},
      {"Compatibility", "Совместимость"},
      {"Refresh", "Обновить"},
      {"Import Local...", "Импорт файла..."},
      {"Not Installed", "Не установлена"},
      {"Installed", "Установлена"},
      {"Downloading", "Загрузка"},
      {"Corrupted", "Повреждена"},
      {"Stem Separation", "Разделение на стемы"},
      {"Beat Detection", "Определение долей"},
      {"Key Detection", "Определение тональности"},
      {"Chord Recognition", "Распознавание аккордов"},
      {"Structure Segmentation", "Сегментация структуры"},
      // First-run wizard
      {"ZYRON - Setup Wizard", "ZYRON — мастер настройки"},
      {"Air-gapped / Offline Only (Zero network usage)", "Полностью офлайн (без обращений к сети)"},
      {"Allow Network (Version check & model downloads only)", "Разрешить сеть (только проверка версии и загрузка моделей)"},
      {"Use Default (./models)", "По умолчанию (./models)"},
      {"Set Custom Directory...", "Своя папка..."},
      {"Scan & Verify All Models", "Проверить все модели"},
      {"Download Missing (Online)", "Скачать недостающие (онлайн)"},
      {"Launch ZYRON DJ", "Запустить ZYRON DJ"},
      {"Back", "Назад"},
      {"Next", "Далее"},
      {"ZYRON is designed offline-first (SPEC %s). Playback, mixing, stems, and analysis work completely without an internet connection.\nChoose your network policy below:", "ZYRON работает прежде всего офлайн (SPEC %s). Воспроизведение, микширование, стемы и анализ полностью работают без интернета.\nВыберите политику работы с сетью:"},
      {"Select where AI model weights (.onnx) are stored on disk:", "Укажите, где на диске хранятся веса моделей ИИ (.onnx):"},
      {"Current path:", "Текущий путь:"},
      {"Current path: models", "Текущий путь: models"},
      {"Current path: custom_models", "Текущий путь: custom_models"},
      {"Model Verification Status", "Состояние проверки моделей"},
      {"All set! Your preferences and model configurations have been saved.\nClick Launch to start mixing tracks.", "Всё готово! Ваши настройки и конфигурация моделей сохранены.\nНажмите «Запустить», чтобы начать микшировать."},
      {"Step %n of 4: %s", "Шаг %n из 4: %s"},
      {"Welcome & Offline Policy", "Добро пожаловать и политика офлайн"},
      {"Model Storage Location", "Папка хранения моделей"},
      {"AI Models Verification", "Проверка моделей ИИ"},
      {"Ready To Launch", "Готово к запуску"},
      {"Verified & ready", "Проверена, готова"},
      {"Checksum mismatch or corrupt", "Контрольная сумма не совпала или файл повреждён"},
      {"Not installed", "Не установлена"},
      {"Present (%s bytes)", "Найден (байт: %s)"},
      {"Corrupt empty file", "Повреждён: пустой файл"},
      {"Missing file", "Файл отсутствует"},
      // AI panels (recommendations, set builder)
      {"AI NEXT-TRACK RECOMMENDATIONS", "РЕКОМЕНДАЦИИ ИИ: СЛЕДУЮЩИЙ ТРЕК"},
      {"Currently playing: None", "Сейчас играет: ничего"},
      {"Currently playing: %a - %t [%b BPM, %k, Energy %e]", "Сейчас играет: %a - %t [%b BPM, %k, энергия %e]"},
      {"Unknown", "Неизвестно"},
      {"Untitled", "Без названия"},
      {"Maintain Energy", "Держать энергию"},
      {"Build Energy (+)", "Нарастить энергию (+)"},
      {"Cool Down (-)", "Снизить энергию (-)"},
      {"Any Energy", "Любая энергия"},
      {"Max Tempo Shift:", "Макс. сдвиг темпа:"},
      {"Match", "Совпад."},
      {"Transition Rationale", "Обоснование перехода"},
      {"Load to Deck", "В деку"},
      {"Harmonic Only (Camelot)", "Только гармонично (Camelot)"},
      {"Generate 60-Min Set", "Создать сет на 60 мин"},
      {"--- Target Energy", "--- Целевая энергия"},
      {"--- Realized Energy", "--- Фактическая энергия"},
      {"AI SET BUILDER & ENERGY CURVE PLANNER", "КОНСТРУКТОР СЕТОВ ИИ И КРИВАЯ ЭНЕРГИИ"},
      {"Profile:", "Профиль:"},
      {"Peak Hour", "Пиковый час"},
      {"Progressive Climb", "Постепенный подъём"},
      {"Wave Pattern", "Волна"},
      {"Warmup", "Разогрев"},
      {"High-Energy Banger", "Мощный бэнгер"},
      {"Duration:", "Длительность:"},
      {"30 Minutes", "30 минут"},
      {"45 Minutes", "45 минут"},
      {"60 Minutes", "60 минут"},
      {"90 Minutes", "90 минут"},
      {"Genre:", "Жанр:"},
      {"Ready to plan set.", "Готов планировать сет."},
      {"Start Time", "Начало"},
      {"Transition Quality", "Качество перехода"},
      {"No builder service or empty catalog.", "Нет сервиса сборки или каталог пуст."},
      // Messages from outside the UI (Automix, Autonomous DJ, engine notices): exact or "%s" templates
      {"Automix needs at least two analysed tracks (%s ready)", "Для автомикса нужно минимум два проанализированных трека (готово: %s)"},
      {"Automix needs at least two analysed tracks (%s ready, analysis is still running: %s tasks left)", "Для автомикса нужно минимум два проанализированных трека (готово: %s, анализ ещё идёт: осталось задач: %s)"},
      {"Loading %s on the free deck...", "Загрузка «%s» на свободную деку..."},
      {"Mixing into %s", "Микс в «%s»"},
      {"Automix stopped: another track was loaded on the playing deck", "Автомикс остановлен: на играющую деку загрузили другой трек"},
      {"The track is not in the library", "Трека нет в библиотеке"},
      {"A mix is already in progress", "Микс уже идёт"},
      {"No free deck: stop one of the other decks first", "Нет свободной деки: сначала остановите одну из других"},
      {"This track has no tempo yet: use Analyse now in its menu", "У трека ещё нет темпа: выберите «Анализировать сейчас» в его меню"},
      {"The playing track has no tempo grid yet, so it cannot be mixed", "У играющего трека ещё нет сетки темпа, поэтому микс невозможен"},
      {"The file could not be decoded", "Файл не удалось декодировать"},
      {"Set planning failed: insufficient matching catalog tracks.", "Не удалось составить сет: в каталоге мало подходящих треков."},
      {"Autonomous DJ stopped.", "Автономный DJ остановлен."},
      {"Autonomous DJ paused.", "Автономный DJ на паузе."},
      {"Autonomous DJ resumed.", "Автономный DJ продолжил работу."},
      {"Autonomous DJ set completed successfully.", "Сет автономного DJ успешно завершён."},
      {"User manual control active on Deck %s", "Ручное управление пользователя: дека %s"},
      {"Could not load the first track: %s", "Не удалось загрузить первый трек: %s"},
      {"Could not load the next track: %s", "Не удалось загрузить следующий трек: %s"},
      {"Loading next track: %s", "Загрузка следующего трека: %s"},
      {"Playing track %s of %s: %s", "Играет трек %s из %s: %s"},
      {"Mixing to next track (%s) via %s", "Микс в следующий трек (%s): %s"},
      {"Bass Swap", "обмен баса"},
      {"Stem Blend", "смешивание стемов"},
      {"Quick Cut", "быстрый обрез"},
      {"Filter Fade", "фильтровый фейд"},
      {"Volume Crossfade", "кроссфейд громкости"},
      {"Stems: wait until the track has finished loading", "Стемы: дождитесь окончания загрузки трека"},
      {"Stems: the neural network is not available in this build", "Стемы: нейросеть недоступна в этой сборке"},
      {"Stems: already being separated", "Стемы: разделение уже идёт"},
      {"Sync: deck %s has no beat grid (analysis is still running or found no beat)", "Синхронизация: у деки %s нет сетки долей (анализ ещё идёт или доли не найдены)"},
      {"Sync: load a second analysed track to sync to", "Синхронизация: загрузите второй проанализированный трек"},
      // DJ sound: keylock, key shift, channel FX, FX hits, loudness, master processing
      {"Keylock (master tempo): changing the tempo keeps the pitch. Off: like a turntable", "Keylock (мастер-темп): смена темпа не меняет тон. Выкл: как на проигрывателе"},
      {"Key down one semitone (the tempo stays)", "Тональность на полутон вниз (темп не меняется)"},
      {"Key up one semitone (the tempo stays)", "Тональность на полутон вверх (темп не меняется)"},
      {"Key shift in semitones | Click: back to 0", "Сдвиг тональности в полутонах | Клик: вернуть в 0"},
      {"The key you hear: the key of the track moved by the key shift (and by the tempo when keylock is off)", "Тональность, которую вы слышите: ключ трека со сдвигом (и с учётом темпа, если keylock выключен)"},
      {"Channel effects: two slots (echo, reverb, flanger, phaser, delay)", "Эффекты канала: два слота (эхо, реверб, флэнжер, фейзер, дилей)"},
      {"None", "Нет"},
      {"Echo", "Эхо"},
      {"Reverb", "Реверб"},
      {"Flanger", "Флэнжер"},
      {"Phaser", "Фейзер"},
      {"Delay", "Дилей"},
      {"FEEDBACK", "ПОВТОРЫ"},
      {"ROOM", "КОМНАТА"},
      {"RATE", "СКОРОСТЬ"},
      {"PARAM", "ПАРАМ"},
      {"WET", "ЭФФЕКТ"},
      {"FX", "FX"},
      {"Effect type of this slot (None empties it)", "Тип эффекта в этом слоте (Нет очищает слот)"},
      {"Switches the effect on or off", "Включает или выключает эффект"},
      {"Air horn", "Горн"},
      {"Siren", "Сирена"},
      {"Riser", "Райзер"},
      {"Downlifter", "Даунлифтер"},
      {"Impact", "Удар"},
      {"Laser", "Лазер"},
      {"FX HITS", "FX-ХИТЫ"},
      {"LEVEL", "УРОВЕНЬ"},
      {"FX hit level (0 to 1)", "Уровень FX-хита (0..1)"},
      {"Plays the effect over the mix (follows the tempo of the playing deck)", "Играет эффект поверх микса (в темпе играющей деки)"},
      {"Auto loudness", "Авто-громкость"},
      {"Levels the loudness of every track you load to a common target (needs the track to be analysed)", "Выравнивает громкость каждого загруженного трека до общей цели (трек должен быть проанализирован)"},
      {"Master glue compressor", "Мастер-компрессор (glue)"},
      {"Gentle compression of the whole mix, like a hardware bus compressor", "Мягкое сжатие всего микса, как у аппаратного шинного компрессора"},
      {"Master limiter", "Мастер-лимитер"},
      {"Stops the output from clipping; keep it on unless something after ZYRON limits", "Не даёт выходу клиппировать; держите включённым, если после ZYRON нет лимитера"},
      {"Stems: acapella blends", "Стемы: смешивание с акапеллой"},
      {"Echo / reverb out", "Уход в эхо / реверб"},
      {"FX hits on drops", "FX-хиты на дропах"},
      {"Separates the tracks into stems ahead of time and mixes with them (needs the stem model)", "Заранее разделяет треки на стемы и микширует с ними (нужна модель стемов)"},
      {"Synthesized air horns, impacts and risers on the drops", "Синтезированные горны, удары и райзеры на дропах"},
      {"Your favourites", "Ваши любимые"},
      {"none yet (pick a transition by hand 3 times)", "пока нет (выберите переход вручную 3 раза)"},
      {"Forget", "Забыть"},
      {"Forget which transitions you picked by hand; the Automix stops favouring them", "Забыть, какие переходы вы выбирали вручную; автомикс перестанет их предпочитать"},
  };
  return table;
}

}  // namespace zyron::ui::i18n
